name: CI
on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Generate lockfile if missing
        run: npm i --package-lock-only
        working-directory: BuzzCord
      - name: Install
        run: npm ci
        working-directory: BuzzCord
      - name: Lint
        run: npm run lint
        working-directory: BuzzCord
      - name: Build
        run: npm run build
        working-directory: BuzzCord
      - name: Test
        run: npm test
        working-directory: BuzzCord
